services:
  - type: web
    name: gym-management-api
    env: python
    pythonVersion: 3.11
    plan: free
    buildCommand: pip install -r requirements-prod.txt
    startCommand: DJANGO_SETTINGS_MODULE=gym_management.settings gunicorn --bind=0.0.0.0:$PORT --workers=4 gym_management.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: gym-management-api.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        fromDatabase:
          name: gym_db
          property: name
      - key: DB_USER
        fromDatabase:
          name: gym_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gym_db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: gym_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gym_db
          property: port

  - type: pserv
    name: gym_db
    env: postgres
    plan: free
    ipAllowList: []
